name: Node.js Package Lint And Test

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"

jobs:
  lint-and-test:
    name: Test on node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: yarn
      - run: yarn lint
      - run: yarn build
      # Unit test
      - run: yarn test
      # Integration test
      - run: cd example && npm i && node example.js
